module.exports = {
  MAX_EXPORT_SIZE: 4096,
  DEFAULT_BG_COLOR: '#FFFFFF',
  GRID_LINE_COLOR: '#999999',
  AXIS_BG_COLOR: '#E3F2FD',
  AXIS_TEXT_COLOR: '#5D4037',
  MIN_FONT_SIZE: 4,
  MIN_SUMMARY_BLOCK: 40
};
